name: todo
description: Todo app using flutter.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  table_calendar: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4
  lint: ^1.8.2 

flutter:
  uses-material-design: true